server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**, /registration/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**, /refunds/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /car-service/v3/api-docs
        name: Car Service
      - url: /user-service/v3/api-docs
        name: User Service
      - url: /order-service/v3/api-docs
        name: Order Service

