server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**, /refunds/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

