server:
  port: 0


spring:
  application:
    name: user-service

  datasource:
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car-rental-microservices?currentSchema=user_service
    username: postgres
    password: postgres

  flyway:
    schemas: user_service
    user: postgres
    password: postgres

  mail:
    host: smtp.yandex.ru
    username: nestydem@yandex.ru
    password: huorjdcocbsfvzoc
    port: 456
    protocol: smtps

mail:
  debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

