server:
  port: 0



spring:
  application:
    name: order-service

  datasource:
    hikari:
      maximum-pool-size: 5
      maxLifetime: 300000
      minimumIdle: 5
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car-rental-microservices?currentSchema=order_service
    username: postgres
    password: postgres

  flyway:
    schemas: order_service
    user: postgres
    password: postgres
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true


  kafka:
    bootstrap-servers: localhost:9092
    order-car-status:
      producer:
        topic: order.car.status

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



openapi:
  service:
    title: Order service documentation #title that you will want to display in the swagger ui
    version: 1.0.0
    description: This is the API for the Order Service of the CarRental project
    url: http://localhost:8765 #api gateway url


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
